;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		evil-append
		evil-backward-word-begin
		evil-delete
		evil-delete-backward-char-and-join
		evil-exit-visual-state
		evil-forward-word-begin
		evil-next-line
		evil-normal-state
		evil-previous-line
		evil-visual-char
		ignore
		lsp-ui-doc--handle-mouse-movement
		markdown-cycle
		mc/remove-fake-cursors
		smex
		string-rectangle
		))

(setq mc/cmds-to-run-once
      '(
		c-electric-paren
		c-indent-line-or-region
		end-of-defun
		evil-backward-char
		evil-change
		evil-force-normal-state
		evil-forward-char
		evil-insert
		evil-mouse-drag-region
		evil-set-marker
		))
